### ISSUE TITLE
在文章底部的 “上一篇” 或 “下一篇” 会暴漏文章入口

### ISSUE THREAD

**Issue by thisnode** [prinsss/hexo-hide-posts#1]
默认主题下，比如隐藏了第五篇文章，在第六篇文章的底部的“上一篇”会暴漏第五篇文章的链接。

**Comment by prinsss** [comment]
这确实是我欠考虑了，感谢你的反馈，我马上着手修复此问题。👍

**Comment by bmitchinson** [comment]
对此有任何更新？ 喜欢这个插件，非常感谢你的工作。

**Comment by chawyehsu** [comment]
这个问题我发现处理起来有点棘手。如果当前文章的上一篇是隐藏文章，那应该如何显示？有两种选择：

- 直接不显示上一篇。这个比较好办，不设置 `post.prev` 就行
- 显示上上一篇文章。这个很麻烦，如果上上一篇文章也是隐藏文章，那就得判断上上上一篇文章。以此类推，直到找到一篇不是隐藏的文章或者没有上一篇文章了为止

**Comment by prinsss** [comment]
@h404bi 是的，我认为遍历直至 `post.prev` 为空而止可能比较好。

@bmitchinson Sorry for putting this issue aside for such a long time, but I'm now busying preparing for my exam. There should be an update with this issue fixed in this week. ;)

**Comment by prinsss** [comment]
已修复 https://github.com/printempw/hexo-hide-posts/commit/0772798e4d28812370b379e4b5da89c25aa8f1a9

**Comment by prinsss** [comment]
新 package [hexo-hide-posts@0.1.0](https://www.npmjs.com/package/hexo-hide-posts) 已发布
