### ISSUE TITLE
无法在其他generators生效

### ISSUE THREAD

**Issue by BSDxxxx** [prinsss/hexo-hide-posts#11]
public_generators: []
这个参数只对index有效，设置其他如：
> hide_posts:
  filter: hide 
  public_generators: [category]  
  noindex: true 

或

> hide_posts:
  filter: hide 
  public_generators: [categories]  
  noindex: true 

front-matter设置：
~~~
---
title: 博客后台管理地址
tags:
  - null
categories:
  - 博客管理
message: '您好, 这里需要密码.'
comment: true
copyright: true
date: 2020-01-09 19:26:10
sitemap: false
top:
photos:
password:
hide: true
---
~~~

在https://host_url/categories/  页面显示暂无分类

**Comment by printempw** [comment]
当你设置 `public_generators: [category]` 时，访问 `https://host_url/categories/博客管理/`，页面上没有显示 `博客后台管理地址` 这篇文章吗？

**Comment by BSDxxxx** [comment]
@printempw 没有

**Comment by BSDxxxx** [comment]
@printempw 有空可以远程帮我看看吗

**Comment by printempw** [comment]
抱歉，回复晚了。😅

尝试运行以下命令：
```
hexo clean
hexo g --debug
```

看看输出中有没有 *Expose hidden posts to generator* 的字样，方便的话最好把完整输出传上来。

另外你说「无法在其他 generators 生效」，把 `public_generators` 设置为 `archive` 之类的话，也是一样的问题吗？

**Comment by BSDxxxx** [comment]
@printempw 重试了几遍，设置为index、archive能显示已隐藏的post，设置为tag和category不能显示已隐藏的post。```hexo -g --debug```输出见：https://pastebin.com/Esnxehvx

**Comment by BSDxxxx** [comment]
对应设置为
```yml
hide_posts:
  filter: hide
  public_generators: [tag]
  noindex: true
```

**Comment by Gzhennaxia** [comment]
+1

**Comment by wonter** [comment]
+1

**Comment by printempw** [comment]
插件已更新至 0.1.1，问题应该解决了

**Comment by Levix** [comment]
> 插件已更新至 0.1.1，问题应该解决了

插件更新至 0.1.1 后，设置 public_generators: [category] 同样不展示已隐藏的文章。

**Comment by Levix** [comment]
> > 插件已更新至 0.1.1，问题应该解决了
> 
> 插件更新至 0.1.1 后，设置 public_generators: [category, tag] 同样不展示已隐藏的文章。
> hexo 主题：https://github.com/izhaoo/hexo-theme-zhaoo

我调整了一下执行命令，发现是没问题了。
`hexo clean && hexo server`
之前是这样的：
`hexo clean && hexo g --debug && hexo server`
