### ISSUE TITLE
Option to hide post completely

### ISSUE THREAD

**Issue by jehy** [prinsss/hexo-hide-posts#19]
I suppose it's not to difficult to hide post completely and disallow direct access for private post.

Of cause, it will only be accessible via source file - but that's what we really mean by "private".

Otherwise, it will get into sitemap, search engines and etc. And will leak to public.

**Comment by prinsss** [comment]
Hi there, if you just want to prevent some posts from being rendered by Hexo, you can simply add a `layout: false` front-matter to the source file. Hexo will then skip it when generating.

**Comment by jehy** [comment]
Hi, @printempw ! Just tried this with latest hexo. Post still rendered, but without theme - just content.

**Comment by prinsss** [comment]
Oops... maybe I got the key wrong. But there should be an option for skipping rendering for specific posts. I will try to find out.

**Comment by prinsss** [comment]
`published: false` should work. (with `render_drafts: false` in your `_config.yml`)
