### ISSUE TITLE
请问能支持 hexo-generator-searchdb 吗？

### ISSUE THREAD

**Issue by tianshuang** [prinsss/hexo-hide-posts#24]
配置了隐藏后本地 search 也搜索不到文章了，在 `_config.yml` 的 `public_generators` 中配置了 `searchdb`  也不起作用。

**Comment by prinsss** [comment]
可以贴一下 `hexo generate --debug` 命令的输出吗？（注意移除敏感信息）

**Comment by prinsss** [comment]
我自己试了一下是没问题的，但需要注意的一点是 `hexo-generator-searchdb` 它注册的 generator 名字不叫 `searchdb`，是 `xml` 和 `json`（分别对应不同文件格式）。所以你需要这样配置：

```yaml
hide_posts:
  public_generators: [archive, xml] # 或者 json
```

**Comment by tianshuang** [comment]
可以了，谢谢，我开始就是配置的 `searchdb`, 可以完善一下 README.md, 😂

**Comment by prinsss** [comment]
要不是去看了下源码我也没想到它用的是这个名字😹
