### ISSUE TITLE
被隐藏博文内hexo-prism-plugin插件不起作用

### ISSUE THREAD

**Issue by ariaxo** [prinsss/hexo-hide-posts#25]
被隐藏博文内代码高亮插件失效

**Comment by prinsss** [comment]
Hi，不好意思之前好像一直没看到这个 issue……😿

现在还有这个问题吗？

**Comment by ariaxo** [comment]
> Hi，不好意思之前好像一直没看到这个 issue……😿
> 
> 现在还有这个问题吗？

已经解决了~感谢
