### ISSUE TITLE
结合hexo-abbrlink如何访问隐藏文章？

### ISSUE THREAD

**Issue by hoey94** [prinsss/hexo-hide-posts#28]
博客使用hexo-abbrlink 修改了url。之后要怎么访问隐藏的文章？

**Comment by hoey94** [comment]
希望能够http://my-domain.me/hidden查看到隐藏的文章，不知道是否能做到？

**Comment by prinsss** [comment]
首先，请使用 `hexo g --debug` 命令，观察调试输出中是否有你所隐藏的文章。`hexo-abbrlink` 应该会输出类似这样的日志：

```
Generated: link [%s] for post [ %s ]
```

其中包含了修改之后的 URL，可以尝试下能否访问。

**Comment by prinsss** [comment]
如果希望有一个页面可以自动收集隐藏的文章，可以尝试把这些文章都放到同一个 Category 下，然后设置：

```yaml
public_generators: ['category']
```

这样对应的文章分类页面上应该就可以显示被隐藏的文章了。

**Comment by prinsss** [comment]
Hello,

hexo-hide-posts 插件已经更新至 0.3.0，支持了更精细的 generator [黑白名单控制](https://github.com/prinsss/hexo-hide-posts/blob/master/README_ZH.md#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE)。

因为这个 issue 较长时间没有新回应，我就先关闭啦。如果还有其他问题，欢迎新开 issue 反馈。:)

**Comment by cdde5** [comment]
测试了以后，没有生成最终的结果：

INFO  Generate link [e3d64f8a] for post [source/_posts/20240815 Game.md][  Game ]
有这个提示，但是没有后面的

INFO  Generated: posts/e3d64f8a.html

也就是说前面提示有了，但是最终的结果里面，在posts文件夹下面没有这个文件。

但是开了百名的，在archives里面是可以看到的，就是页面上的归档是可以看到的，有什么办法解决不，非常感谢
