### ISSUE TITLE
本插件后续更新计划

### ISSUE THREAD

**Issue by prinsss** [prinsss/hexo-hide-posts#3]
一系列 TODO，旨在使本插件更为通用。

- [x] 由 `hexo-sage-posts` 更名为 `hexo-hide-posts`
  - 说实话我也不知道当初为什么选了这个名字，想想还是改一下好
  - 变更将包括 GitHub 仓库名与 npm 包名
- [x] 提供自定义隐藏文章的 filter 选项 #2
  - 如 `sage: true` 或者 `hide: true`
- [x] 修复「上一篇」「下一篇」造成文章入口暴露的问题 #1 
- [x] 允许指定对特定的某些 generator 隐藏文章
  - 如仅对 `index` 隐藏（即在首页隐藏指定文章）、仅对 `feed` 隐藏等

预计本周末开始着手开发（欢迎 PR）。

**Comment by bmitchinson** [comment]
Looking forward to these changes! Thanks for all your hard work.

**Comment by bmitchinson** [comment]
@printempw any updates on these changes?

**Comment by prinsss** [comment]
Sorry but, nope. I am so busy these days that I have no time to work on this. But I will try to start implementing these features as soon as possible. 😥

**Comment by prinsss** [comment]
All changes committed. Sorry for being late.

**Comment by prinsss** [comment]
The new package [hexo-hide-posts@0.1.0](https://www.npmjs.com/package/hexo-hide-posts) is published! Closing this issue. ;)

**Comment by bmitchinson** [comment]
Yay! Thanks for you amazing work.
