### ISSUE TITLE
如何設定兩種 public genterator?

### ISSUE THREAD

**Issue by PttCodingMan** [prinsss/hexo-hide-posts#30]
我想要一部份文章套用   public_generators: ['xml', 'json']
另一些文章套用  public_generators: ['index', 'tag', 'category', 'archive', 'xml', 'json']

請問是否存在某種方式可以達到？

**Comment by prinsss** [comment]
目前好像没有这样的功能。后续可以考虑支持下文章维度的 `public_generators` 设置，不过需要一定时间。

另外看你这个需求，设置 `public_generators: ['index', 'tag', 'category', 'archive', 'xml', 'json']` 的文章，好像和普通未隐藏的文章没有什么区别？是希望达到怎样的效果呢？

**Comment by PttCodingMan** [comment]
嗨，我的想像中希望可以達到兩種隱藏方式

1. 正常出現在 blog 中，但不出現在 RSS, sitemap 等功能裡
2. 在 blog 中無法找到，但可以透過文章網址直接存取文章

感謝你的回應 :D

**Comment by prinsss** [comment]
Hi,

hexo-hide-posts 插件已经更新至 0.4.0，支持了更精细的 [自定义 ACL 函数](https://github.com/prinsss/hexo-hide-posts/blob/master/README_ZH.md#%E8%87%AA%E5%AE%9A%E4%B9%89-acl-%E5%87%BD%E6%95%B0)。

你可以通过自定义 ACL 函数实现你需要的功能（在博客的 `scripts` 目录中创建以下文件）：

```js
// FILE: scripts/acl.js

hexo.config.hide_posts.acl_function_per_post = function (post, generatorName) {
  // 在 front-matter 中标记为 `acl: no-rss` 的文章不会出现在 RSS 和 sitemap 中
  if (post.acl === 'no-rss') {
    return generatorName !== 'atom' && generatorName !== 'sitemap';
  }

  // 标记为 `hidden: true` 的文章只能通过网址访问
  if (post.hidden) {
    return false;
  }

  // 其他文章正常显示
  return true;
}
```

如果新功能有任何问题，欢迎反馈。:)

**Comment by PttCodingMan** [comment]
Many thanks.
