### ISSUE TITLE
Plugin has problem when  layout is disabled in front matter

### ISSUE THREAD

**Issue by seiji68** [prinsss/hexo-hide-posts#35]
When some posts need to show as plain text, layout is disabled. It may be lack of tags for this plugin. Can this be solved with some tricks or work around?

**Comment by prinsss** [comment]
Hi there,

Thank you for the bug report. I've published a new beta version of the plugin which should fix the problem when setting `layout: false` in front-matter. Give it a try and let me know if it works!

```bash
npm install hexo-hide-posts@0.4.3-beta.1
```

**Comment by prinsss** [comment]
BTW, the `noindex: true` feature may not work for plain text posts since they will not be rendered to full HTML pages.

**Comment by seiji68** [comment]
Hi prinsss, `hexo-hide-posts@0.4.3-beta.1` works very well, although it is a pity for the no index feature.

**Comment by prinsss** [comment]
There is a workaround for this though.

Create a `scripts` folder in your blog's directory, and create a `.js` file inside. Then paste these codes into it:

```js
// FILE: scripts/after_post_render.js

// The `after_render:html` filter does not trigger on posts without a layout,
// thus we need to use the `after_post_render` filter to handle these cases.
hexo.extend.filter.register("after_post_render", function (data) {
  // Skip if the post is not marked as hidden.
  if (!data.hidden) {
    return data;
  }

  // Fix the HTML document structure for posts without a layout and add a noindex meta tag.
  if (!data.layout || data.layout === "false" || data.layout === "off") {
    data.content = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${data.title}</title>
  <meta name="robots" content="noindex">
</head>
<body>
  ${data.content}
</body>
</html>
`;
  }

  return data;
});
```

Save the file, and run `hexo clean && hexo g` to see if it works.

![CleanShot 2024-04-06 at 19 04 36](https://github.com/prinsss/hexo-hide-posts/assets/11206497/c3590a24-bc7e-44ef-941d-070d9e3c7fb5)

**Comment by seiji68** [comment]
Wow, thank you for you kindly help! This do the trick : )
