### ISSUE TITLE
使用acl配置仅可通过链接访问后仍可在主页“最新文章”组件看到、访问此文章

### ISSUE THREAD

**Issue by Meowjay1110** [prinsss/hexo-hide-posts#36]
效果、配置见下图，主题使用butterfly。已执行hexo clean，插件版本为最新。
![image](https://github.com/prinsss/hexo-hide-posts/assets/109258169/192c2238-7bb3-4aee-8a8d-130bd439bf81)
![image](https://github.com/prinsss/hexo-hide-posts/assets/109258169/b2676e1c-4498-41dc-83f2-290678edf603)
![image](https://github.com/prinsss/hexo-hide-posts/assets/109258169/4cde56ee-046d-4bbe-a66b-c7be88c6be88)

**Comment by Meowjay1110** [comment]
补充：使用与配置文件（_config.yml）中配置的标签一致时无此问题

**Comment by prinsss** [comment]
Hi，我看了一下 butterfly 主题侧边栏小工具的实现，目前 ACL 可能还没有覆盖到这种场景。

请先尝试一下这样配置，看下能否满足你的需求：

```js
hexo.config.hide_posts.acl_function_per_post = function (post, generatorName) {
  if (post.linkonly) {
    return false;
  }

  if (post.hidden) {
    return generatorName !== 'index';
  }

  return true;
};
```

文章配置：

```markdown
---
title: Happy Birthday (ACL Applied)
date: 2024-04-10
# 需要同时存在
hidden: true
linkonly: true
---

Happy Birthday! 🎉🎂🎈🎁
```

**Comment by Meowjay1110** [comment]
试了下，小组件那里没有了，但是出现在了其他地方（例如时间轴）

**Comment by prinsss** [comment]
> 试了下，小组件那里没有了，但是出现在了其他地方（例如时间轴）

时间轴页面是指 archives 页面吗？我这里没有复现你说的情况。你有按照我上面发的那样调换脚本中两个 `if` 语句的位置吗？

**Comment by Meowjay1110** [comment]
调换之后问题就解决了，谢谢大佬！
