### ISSUE TITLE
会导致在打草稿时 hexo-server 不能热刷新文章

### ISSUE THREAD

**Issue by chawyehsu** [prinsss/hexo-hide-posts#4]
不知道你能否复现。

```
hexo new draft just-a-draft
hexo clean && hexo s --draft --debug
```

just-a-draft.md
```
---
title: just-a-draft
draft: true
hidden: true
comments: false
---
```

编辑 just-a-draft.md，hexo-server 热刷新后，文章会无法访问（还有一种情况是，文章一直是刚启动 hexo server 时的状态，编辑更新的内容不出现）。

**Comment by HMAU-AC** [comment]
这个问题要怎么解决啊，我也出现了这个问题 急急急

**Comment by prinsss** [comment]
目前用最新的 commit 测试似乎没有这个问题

**Comment by prinsss** [comment]
新 package [hexo-hide-posts@0.1.0](https://www.npmjs.com/package/hexo-hide-posts) 已发布

如果最新版本依然有此问题，请 reopen 这个 issue。
