### ISSUE TITLE
Suggest better document

### ISSUE THREAD

**Issue by zhanghuimeng** [prinsss/hexo-hide-posts#5]
I thought that hidden posts would not be visible even locally (when you do `hexo s`), but actually they do, so I thought there was a bug with this plguin. But it seems that when I push my posts online, they do get hidden in a good way.

[Example](https://zhanghuimeng.github.io/blog-example/hexo-sage-posts-test/)

So I suggest you write this clearly in the document, or more people might get confused. It's a feature, not a bug ;-)

**Comment by zhanghuimeng** [comment]
嗯，当我没说，这个插件在我当前的博客上确实不work，而且我不知道是什么原因……

**Comment by prinsss** [comment]
照理来说就算是本地也不会显示的……

**Comment by prinsss** [comment]
The new package [hexo-hide-posts@0.1.0](https://www.npmjs.com/package/hexo-hide-posts) is published, and I am closing this issue now.

Feel free to reopen it if you still encounter this issue.
