### ISSUE TITLE
是否有一个Hidden文章的列表？

### ISSUE THREAD

**Issue by sluk3r** [prinsss/hexo-hide-posts#6]
现在使用Sage管理隐藏文章， 后面可能随着影藏文章的变多， 一些链接自己也记不住了。 

这样， 针对这个问题， 是否考虑添加隐藏文章的列表， 方便查看已经隐藏的文章？ 

当然，现在想到一些方法是， 使用某些Linux命令来搜索sage的关键字。这个方法可以达到效果，但繁琐。 
所以还是期望在Sage中能有这样一个功能。

**Comment by prinsss** [comment]
现在你可以通过命令行运行 `hexo hidden:list` 来显示隐藏文章的列表。https://github.com/printempw/hexo-hide-posts/commit/f1fc032a0ea6148c9782af5c73050ccbca00f4f6

如果你是主题开发者，可以直接在模板中通过 `site.hidden_posts` 获取隐藏文章。

**Comment by prinsss** [comment]
新 package [hexo-hide-posts@0.1.0](https://www.npmjs.com/package/hexo-hide-posts) 已发布
