### ISSUE TITLE
隐藏文章的Toc也没有显示了

### ISSUE THREAD

**Issue by sluk3r** [prinsss/hexo-hide-posts#7]
在使用过程中， 发现设置了隐藏后的文章， Toc也没有了。 

隐藏掉Top，不知这是一个正常的功能， 还是一个被躺枪的牵连？

**Comment by prinsss** [comment]
可以提供一下你目前正在使用的主题信息吗？

**Comment by sluk3r** [comment]
> 可以提供一下你目前正在使用的主题信息吗？

您好， 主题是：NexT.Muse v5.1.4

**Comment by sluk3r** [comment]
这篇文章（https://sluk3r.github.io/2019/08/26/first-hidden-blg/）设置是隐藏了的， 不过打开后Toc没有了

**Comment by prinsss** [comment]
你的这篇文章里没有包括任何标题元素呀……

就算不设置为隐藏文章应该也是不会显示 TOC 的。

**Comment by prinsss** [comment]
因为长时间没有后续回复，我将暂时关闭这个 issue。

如果此问题依然存在，请直接回复或者 reopen ;)
