### ISSUE TITLE
输入Url后， 也不能查看？

### ISSUE THREAD

**Issue by sluk3r** [prinsss/hexo-hide-posts#8]
能不能彻底隐藏某篇文章？ 即当隐藏的文章，被知道URL后，在浏览器里访问时， 也会给一个恰当的反馈， 而不是像现在一样，可以正常查看？

**Comment by prinsss** [comment]
抱歉，我没看懂你的意思……

本插件的目的就是让文章不显示在列表中，而可以通过链接正常访问。如果也不希望其他人通过链接访问的话，或许直接设置 `published: false` 会更好一些。

**Comment by sluk3r** [comment]
> 抱歉，我没看懂你的意思……
> 
> 本插件的目的就是让文章不显示在列表中，而可以通过链接正常访问。如果也不希望其他人通过链接访问的话，或许直接设置 `published: false` 会更好一些。

多谢，通过您的回复， 学到了“published: false”

**Comment by sluk3r** [comment]
使用“published: false”问题已解决， 多谢。
