### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by janvaniperen** [prinsss/hexo-hide-posts#9]
Am I right that this does not work for a page? Can I change that somewhere so it does allow for pages to be hidden?

**Comment by prinsss** [comment]
No, it only works for posts now. I'll see if I can add pages support.

**Comment by prinsss** [comment]
Hello there! Sorry for being late \*_\*

But as far as I can see, pages are currently not being processed by most of the generators (archives, categories, tags, feeds, etc.). So in most cases, pages should be only accessible by their permanent links...

Would you please tell me what your situation is, and how is this plugin supposed to support hiding pages? Thank you!

**Comment by janvaniperen** [comment]
on my site I created a page that should not be indexed and should only be found when people scan a QR code on my business card. It leads them here: https://janvaniperen.com/mip/
Hence the need to hide from search engines/indexing

**Comment by prinsss** [comment]
Okay, I see. I will try to implement it in further release. :)

For now, here is a workaround:

Add `<!-- flag of hidden posts -->` to the Markdown source of page you want to hide, then the plugin will read it and add a `<meta name="robots" content="noindex">` for that page. 

Check generated HTML to see if it works.

**Comment by janvaniperen** [comment]
Mmmm, does not seem to work for me. But now understand I can just manually add a `robots.txt` file and just exclude it there... when it's just a couple of pages it is an easier solution I guess...

**Comment by prinsss** [comment]
Apologies for the long period of inactivity. The plugin was just updated to 0.1.1, and it should support hiding pages now. Feel free to reopen if there is any problem.
